config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'dashboard', to: 'users#dashboard', as: :dashboard

 resources :plants do

  resources :bookings, only: [:create]
  resources :wishes, only: [:create, :destroy]

 end

resources :bookings, only: [:update, :destroy] do
  resources :reviews, only: [:new, :create]
 end

resources :reviews, only: [:show,:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :plant
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :address ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :wishes, dependent: :destroy
  validates :name, presence: true
  validates :daily_price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plants, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :wishes, dependent: :destroy
  # validates :first_name, presence: true
  # validates :last_name, presence: true
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :plant
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    dashboard_path
  end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  # this is part of the setup of pundit.
  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :update, :destroy]

  def create
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.plant = @plant
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  def destroy
    authorize @booking
    @booking.delete
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    if params[:query].present?
      @plants = policy_scope(Plant).global_search(params[:query])
    else
      @plants = policy_scope(Plant)
    end
    @markers = @plants.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { plant: plant })
      }
    end
  end

  def show
    @plant = Plant.find(params[:id])
    @booking = Booking.new
    authorize @plant
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    authorize @plant
    if @plant.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @plant = Plant.find(params[:id])
    authorize @plant
  end

  def update
    @plant = Plant.find(params[:id])
    authorize @plant
    if @plant.update(plant_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    authorize @plant
    @plant.destroy
    redirect_to dashboard_path
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :species, :instructions, :daily_price, :image, :danger_level)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    authorize @review
  end

  def update
    @review = Review.find(params[:id])
    authorize @review
    if @review.update(review_params)
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    authorize @review

    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:stars, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @my_own_plants = current_user.plants
    # @my_own_plants = Plant.where(user: current_user)
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @my_wishes = current_user.wishes
    @reviews = policy_scope(Review).order(created_at: :desc)
    authorize @my_own_plants
    authorize @bookings
    authorize @my_wishes
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def show
    @wish = Wish.find(params[:id])
    authorize @wish
  end

  def create
    @wish = Wish.new(plant_id: params[:plant_id], user_id: current_user)
    @wish.user = current_user
    @wish.save
    authorize @wish
  end

  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy
    authorize @wish
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@plant, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking</h1>

<p><%= @booking.plant.name %></p>

  <div class="booking-form col-3">
    <%= simple_form_for [@plant, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.button :submit, "Edit", class: "btn btn-green" %>
    <% end %>
  </div>

<%= link_to "Back", dashboard_path %>
<%= link_to "Delete", booking_path(@booking),
    method: :delete,
    data: { confirm: "Are you sure?" }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Borrow My Cactus</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940)">
  <div class="banner-container">
    <h1>Borrow My Cactus</h1>
    <%= link_to new_user_session_path, class: "btn btn-red" do %> Login <% end %>
  </div>
</div>

app/views/plants/_info_window.html.erb
<h3><%= plant.name %></h3>
  <p><%= plant.address %></p>
  <p><%= plant.daily_price %></p>

app/views/plants/edit.html.erb
<%= render 'shared/new', plant: @plant %>

app/views/plants/index.html.erb
<div class="text-center">
  <h2>Search for Plants in Your Area</h2>
</div>

  <!-- Search Bar -->
<div class="margin-search-bar">
  <%= render 'shared/search_bar' %>
</div>

<div class="search-container d-flex">

  <div class="cards-container" style="border-color: white;">
    <% if @plants.empty? %>
      <div style= "margin-top:30%; color: rgb(30,30,30);">
        Sorry, we don't find any cactus for you...Try again!
      </div>
    <% else %>
      <% @plants.each do |plant| %>
        <div class="cactus card">
            <div class="wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= plant.image %>)">
              <div class="header">
                <div class="date">
                  <span class="day"></span>
                  <span class="month"><%= plant.daily_price %></span>
                  <span class="year">per day</span>
                </div>
                <ul class="menu-content">
                  <li> <%= link_to "", plant_wishes_path(plant),  method: :post, class: "fa fa-heart-o" %><span>Save</span>
                </ul>
              </div>
              <div class="data">
                <div class="content">
                  <span class="author"><%= plant.user.first_name %></span>
                  <h1 class="title"><%= link_to plant.name, plant_path(plant)  %></h1>
                  <p class="text"><%= plant.instructions %></p>
                  <br>
                  <%= link_to "Book Now", plant_path(plant), class: "button" %>
                </div>
              </div>
            </div>
          </div>
     <% end %>
    <% end %>
  </div>
  <div
      style="    position: sticky;
    top: 20px;"
      id="map"
      class="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/plants/new.html.erb
<%= render'shared/new', plant: @plant%>

app/views/plants/show.html.erb
<div class="container">
  <div class="row">
    <div class="plant-image col-md-6" style="background-image: url(<%= @plant.image %>)"></div>
    <div class="info-container col-md-6">
      <h1><%= @plant.name %></h1>
      <p><strong>Daily Price: <%= @plant.daily_price %></strong></p>
      <p>Owner: <%= @plant.user.first_name %> <%= @plant.user.last_name %> | <%= @plant.address %> </p>
      <p>Specie: <%= @plant.species %></p>
      <p>Danger Level: <%= @plant.danger_level %></p>
      <p>Instructions: <%= @plant.instructions %></p>
      <div class="wrapper">
        <% if policy(@plant).edit? %>
          <%= link_to edit_plant_path(@plant), class: "btn btn-green" do %> Edit <% end %>
        <% end %>
        <% if policy(@plant).destroy? %>
          <%= link_to plant_path(@plant), method: :delete,  class: "btn btn-green" do %> Delete <% end %>
        <% else %>
          <div class="booking-form">
            <%= simple_form_for [@plant, @booking] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.button :submit, "Book Now", class: "btn btn-green" %>
            <% end %>
          </div>
        <% end %>
        <%= link_to plants_path, class: "btn btn-light" do %> Back <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@booking, @review] do |f| %>
<%= f.input :stars %>
<%= f.input :content %>
<%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/index.html.erb
<h3>All Reviews</h3>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.stars %>
      <%= review.content %>
      <% if policy(review).edit? %>
      <%= link_to "Edit", edit_review_path(review) %>
      <% end %>
      <% if policy(review).destroy? %>
      <%= link_to "Delete", review_path(review),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= image_tag("cactus.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Explore", plants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a plant", new_plant_path , class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("cactus.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path , class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_new.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1493957988430-a5f2e15f39a3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')">
  <div class="banner-container  white-container">
    <h3 class="text-center p-3">Add a new plant</h3>
    <div class="row plant-form d-flex">
      <div class="col-lg-6">
        <%= simple_form_for plant do |f| %>
          <%= f.input :name %>
          <%= f.input :species %>
          <%= f.input :instructions %>
          <%= f.input :daily_price %>
          <%= f.input :image %>
          <%= f.input :danger_level %>
          <%= f.button :submit, "Create a new plant", class: "btn btn-red"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
  <form class="form-inline md-form form-sm active-red active-red mt-2">
    <i class="fas fa-search" aria-hidden="true"></i>
    <%= form_tag plants_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a cactus"
      %>
      <%= submit_tag "Search", class: "btn-transparent" %>
    <% end %>
  </form>

app/views/users/_destroy.js.erb
document.querySelector("[data-restaurant-id='<%= @restaurant.id %>']")
  .remove();

app/views/users/dashboard.html.erb
<div class="center-content" style="background-image: url(https://images.unsplash.com/photo-1459156212016-c812468e2115?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1549&q=80)">

  <div class="dashboard-container">

    <!-- Title -->
    <div class="wrapper main-title">
      <h1>Hi Paul, welcome back!</h1>
      <h3>What do you want to do today?</h3>
    </div>

    <!-- Buttons -->
    <div class="wrapper buttons-wrapper">
     <!--  Explore Button -->
      <div class="svg-wrapper">
        <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
          <rect id="shape" height="40" width="150" />
          <div id="text">
            <%= link_to plants_path do %>
           <span class="spot"></span>Explore
            <% end %>
          </div>
        </svg>
      </div>
      <!-- Add Plant Button -->
      <div class="svg-wrapper">
        <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
          <rect id="shape" height="40" width="150" />
          <div id="text">
            <%= link_to new_plant_path do %>
            <span class="spot"></span>Add Plant
            <% end %>
          </div>
        </svg>
      </div>


    <!-- User Cactuses -->
    <div class = "cactus-wrapper">
      <div class = "title-wrapper">
        <h2> Paul cacti</h2>
      </div>
      <div class="row">
        <% @my_own_plants.last(3).each do |plant| %>
          <div class="cactus card">
            <div class="wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= plant.image %>)">
              <div class="header">
                <div class="date">
                  <span class="day"></span>
                  <span class="month"><%= plant.daily_price %></span>
                  <span class="year">per day</span>
                </div>
                <ul class="menu-content">
                  <li> <%= link_to "", plant_path(plant),  method: :delete, class: "far fa-trash-alt" %>
                  <span>Delete</span>
                </ul>
              </div>
              <div class="data">
                <div class="content">
                  <span class="author"><%= plant.user.first_name %></span>
                  <h3 class="title"><%= link_to plant.name, plant_path(plant)%></h3>
                  <p class="text"><%= plant.instructions %></p>
                  <br>
                  <%= link_to "Edit plant", edit_plant_path(plant), class: "button" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>

    <!-- Bookings -->
    <div class = "wrapper">
      <div class="title-wrapper">
        <h3>Paul, you are borrowing these plants:</h3>
      </div>
      <div class="borrow-content">

    <div class = "padding ">
        <% @bookings.first(3).each do |booking| %>
          <div class="booking">
            <img src="<%= booking.plant.image %>" />
            <div class="booking-infos">
              <h2>Return me in <strong><%= (booking.end_date - Date.today).to_i %> days! </strong></h2>
              <p>You borrowed <%= booking.plant.name %> from <strong><%= booking.plant.user.first_name%></strong></p>


            </div>
            <div id="icon"><%=link_to image_tag("edit.png", style:"height: 21px; width: 21px;"), plant_path(booking.plant) %></div>
          </div>
        <% end %>
        </ol>
      </div>
    </div>
     </div>

    <div class="padding">
      <h2>Reviews</h2>
      <ul>
        <% @reviews.first(5).each do |review| %>
          <div class="review">
              <div> <strong><%= review.stars %>/5</strong> &ensp;<%= review.content %>
              <p>by <%= review.booking.user.first_name %> <%= review.booking.user.last_name %></p>
              </div>
          </div>
        <% end %>
      </ul>
    </div>

    <div class="padding">
      <h2>Wishlist</h2>

      <div class="row" style="border-color: white;">
        <% @my_wishes.each do |wish| %>
          <div class="cactus card">
            <div class="wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= wish.plant.image %>)">
              <div class="header">
                <div class="date">
                  <span class="day"></span>
                  <span class="month"><%= wish.plant.daily_price %></span>
                  <span class="year">per day</span>
                </div>
                <ul class="menu-content">
                  <li> <%= link_to "", plant_wish_path(wish.plant, wish),  method: :delete, class: "fa fa-heart-o" %><span>Delete</span>
                </ul>
              </div>
              <div class="data">
                <div class="content">
                  <span class="author"><%= wish.plant.user.first_name %></span>
                  <h1 class="title"><%= link_to wish.plant.name, plant_path(wish.plant)  %></h1>
                  <p class="text"><%= wish.plant.instructions %></p>
                  <br>
                  <%= link_to "Book Now", plant_path(wish.plant), class: "button" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>